Repository BasePractice/algorithms-and-data-structures-2022, pull requests merged in 2022-12, with the labels that each got.

#152 Практические работы Давыдов Денис КВБО-03-21
  students/21K0602/21K0602-p23/pom.xml
  students/21K0602/21K0602-p23/src/main/java/ru/mirea/practice/task1/ArrayQueue.java
  students/21K0602/21K0602-p23/src/main/java/ru/mirea/practice/task1/ArrayQueueAdt.java
  students/21K0602/21K0602-p23/src/main/java/ru/mirea/practice/task1/ArrayQueueModule.java
  students/21K0602/21K0602-p23/src/main/java/ru/mirea/practice/task1/Main.java
  students/21K0602/21K0602-p23/src/main/java/ru/mirea/practice/task1/README.txt
  students/21K0602/21K0602-p23/src/main/java/ru/mirea/practice/task2/AbstractQueue.java
  students/21K0602/21K0602-p23/src/main/java/ru/mirea/practice/task2/ArrayQueue.java
  students/21K0602/21K0602-p23/src/main/java/ru/mirea/practice/task2/LinkedQueue.java
  students/21K0602/21K0602-p23/src/main/java/ru/mirea/practice/task2/Node.java
  students/21K0602/21K0602-p23/src/main/java/ru/mirea/practice/task2/Queue.java
  students/21K0602/21K0602-p24/pom.xml
  students/21K0602/21K0602-p24/src/main/java/ru/mirea/practice/task1/Complex.java
  students/21K0602/21K0602-p24/src/main/java/ru/mirea/practice/task1/ComplexAbstractFactory.java
  students/21K0602/21K0602-p24/src/main/java/ru/mirea/practice/task1/ConcreteFactory.java
  students/21K0602/21K0602-p24/src/main/java/ru/mirea/practice/task1/Main.java
  students/21K0602/21K0602-p24/src/main/java/ru/mirea/practice/task2/solution1/AbstractChairFactory.java
  students/21K0602/21K0602-p24/src/main/java/ru/mirea/practice/task2/solution1/ChairFactory.java
  students/21K0602/21K0602-p24/src/main/java/ru/mirea/practice/task2/solution2/Chair.java
  students/21K0602/21K0602-p24/src/main/java/ru/mirea/practice/task2/solution2/ChairFactory.java
  students/21K0602/21K0602-p24/src/main/java/ru/mirea/practice/task2/solution2/FunctionalChair.java
  students/21K0602/21K0602-p24/src/main/java/ru/mirea/practice/task2/solution2/FunctionalChairFactory.java
  students/21K0602/21K0602-p24/src/main/java/ru/mirea/practice/task2/solution2/MagicChair.java
  students/21K0602/21K0602-p24/src/main/java/ru/mirea/practice/task2/solution2/MagicChairFactory.java
  students/21K0602/21K0602-p24/src/main/java/ru/mirea/practice/task2/solution2/Main.java
  students/21K0602/21K0602-p24/src/main/java/ru/mirea/practice/task2/solution2/VictorianChair.java
  students/21K0602/21K0602-p24/src/main/java/ru/mirea/practice/task2/solution2/VictorianChairFactory.java
  students/21K0602/21K0602-p24/src/main/java/ru/mirea/practice/task3/CreateImageDocument.java
  students/21K0602/21K0602-p24/src/main/java/ru/mirea/practice/task3/CreateMusicDocument.java
  students/21K0602/21K0602-p24/src/main/java/ru/mirea/practice/task3/CreateTextDocument.java
  students/21K0602/21K0602-p24/src/main/java/ru/mirea/practice/task3/DataBase.java
  students/21K0602/21K0602-p24/src/main/java/ru/mirea/practice/task3/File.java
  students/21K0602/21K0602-p24/src/main/java/ru/mirea/practice/task3/IcreateDocument.java
  students/21K0602/21K0602-p24/src/main/java/ru/mirea/practice/task3/Idocument.java
  students/21K0602/21K0602-p24/src/main/java/ru/mirea/practice/task3/ImageDocument.java
  students/21K0602/21K0602-p24/src/main/java/ru/mirea/practice/task3/MusicDocument.java
  students/21K0602/21K0602-p24/src/main/java/ru/mirea/practice/task3/TextDocument.java
  students/21K0602/21K0602-p25/README.txt
  students/21K0602/21K0602-p25/pom.xml
  students/21K0602/21K0602-p25/src/main/java/ru/mirea/practice/task1/Main.java
  students/21K0602/21K0602-p25/src/main/java/ru/mirea/practice/task2/Main.java
  students/21K0602/21K0602-p25/src/main/java/ru/mirea/practice/task3/CostParser.java
  students/21K0602/21K0602-p25/src/main/java/ru/mirea/practice/task4/Main.java
  students/21K0602/21K0602-p25/src/main/java/ru/mirea/practice/task5/Calendar.java
  students/21K0602/21K0602-p25/src/main/java/ru/mirea/practice/task5/Main.java
  students/21K0602/21K0602-p25/src/main/java/ru/mirea/practice/task6/EmailChecker.java
  students/21K0602/21K0602-p25/src/main/java/ru/mirea/practice/task7/Main.java
  students/21K0602/21K0602-p25/src/main/java/ru/mirea/practice/task7/PasswordChecker.java
  students/21K0602/21K0602-p25/src/main/java/ru/mirea/practice/task8/Filter.java
  students/21K0602/21K0602-p25/src/main/java/ru/mirea/practice/task8/Main.java
  students/21K0602/21K0602-p25/src/main/java/ru/mirea/practice/task9/Dictionary.java
  students/21K0602/21K0602-p25/src/main/java/ru/mirea/practice/task9/Main.java
  students/21K0602/21K0602-p26/pom.xml
  students/21K0602/21K0602-p26/src/main/java/ru/mirea/practice/task1/Main.java
  students/21K0602/21K0602-p26/src/main/java/ru/mirea/practice/task2to3/Main.java
  students/21K0602/21K0602-p26/src/main/java/ru/mirea/practice/task2to3/Node.java
  students/21K0602/21K0602-p26/src/main/java/ru/mirea/practice/task2to3/UserList.java
  students/21K0602/pom.xml
Labels: проверка

#162 Практические работы Давыдов Дениса КВБО-03-21
  students/21K0602/21K0602-p27/pom.xml
  students/21K0602/21K0602-p27/src/main/java/ru/mirea/practice/task/HashTab.java
  students/21K0602/21K0602-p27/src/main/java/ru/mirea/practice/task/Test.java
  students/21K0602/pom.xml
Labels: проверка

#165 Практические работы Давыдов Денис КВБО-03-21
  students/21K0602/21K0602-p28/pom.xml
  students/21K0602/21K0602-p28/src/main/java/ru/mirea/practice/task1/Main.java
  students/21K0602/21K0602-p28/src/main/java/ru/mirea/practice/task2/Main.java
  students/21K0602/21K0602-p28/src/main/java/ru/mirea/practice/task3/Main.java
  students/21K0602/21K0602-p29/pom.xml
  students/21K0602/21K0602-p29/src/main/java/ru/mirea/practice/task1/Main.java
  students/21K0602/21K0602-p30/pom.xml
  students/21K0602/21K0602-p30/src/main/java/ru/mirea/practice/task1/Main.java
  students/21K0602/21K0602-p30/src/main/java/ru/mirea/practice/task1/Tree.java
  students/21K0602/21K0602-p30/src/main/java/ru/mirea/practice/task2/Huffman.java
  students/21K0602/21K0602-p30/src/main/java/ru/mirea/practice/task2/Main.java
  students/21K0602/21K0602-p30/src/main/java/ru/mirea/practice/task2/Tree.java
  students/21K0602/21K0602-p32/pom.xml
  students/21K0602/21K0602-p32/src/main/java/ru/mirea/practice/task1/JonsTrot.java
  students/21K0602/21K0602-p32/src/main/java/ru/mirea/practice/task1/Main.java
  students/21K0602/pom.xml
Labels: проверка

#198 Практические 28-30.2 Корсунов Иван КВБО-02-21
  students/21K0637/21K0637-p28/src/main/java/mirea/practice/task1/Main.java
  students/21K0637/21K0637-p28/src/main/java/mirea/practice/task2/Main.java
  students/21K0637/21K0637-p28/src/main/java/mirea/practice/task2/Map.java
  students/21K0637/21K0637-p28/src/main/java/mirea/practice/task3/Main.java
  students/21K0637/21K0637-p29/pom.xml
  students/21K0637/21K0637-p29/src/main/java/mirea/practice/citiesandroads/Solution.java
  students/21K0637/21K0637-p30.1/pom.xml
  students/21K0637/21K0637-p30.1/src/main/java/mirea/practice/task1/Main.java
  students/21K0637/21K0637-p30.1/src/main/java/mirea/practice/task1/Node.java
  students/21K0637/21K0637-p30.1/src/main/java/mirea/practice/task2/HuffmansAlgorithm.java
  students/21K0637/21K0637-p30.1/src/main/java/mirea/practice/task2/Main.java
  students/21K0637/21K0637-p30.2/pom.xml
  students/21K0637/21K0637-p30.2/src/main/java/mirea/practice/BinarySearchTree.java
  students/21K0637/21K0637-p30.2/src/main/java/mirea/practice/Main.java
  students/21K0637/21K0637-p31/pom.xml
  students/21K0637/pom.xml
Labels: проверка, вопросы

#197 Практическая работа 25
  students/21K0710/21K0710-p25/pom.xml
  students/21K0710/21K0710-p25/src/main/java/ru/mirea/worktwentyfive/task2/Main.java
  students/21K0710/21K0710-p25/src/main/java/ru/mirea/worktwentyfive/task5/Main.java
  students/21K0710/21K0710-p25/src/main/java/ru/mirea/worktwentyfive/task6/Main.java
  students/21K0710/pom.xml
Labels: проверка, анализ

#189 Добавлены практические работы 27-32
  students/21K0623/21K0623-p27/pom.xml
  students/21K0623/21K0623-p27/src/main/java/ru/mirea/practice/solutiontask1/Hashtab.java
  students/21K0623/21K0623-p27/src/main/java/ru/mirea/practice/solutiontask1/Main.java
  students/21K0623/21K0623-p27/src/main/java/ru/mirea/practice/solutiontask1/Node.java
  students/21K0623/21K0623-p28/pom.xml
  students/21K0623/21K0623-p28/src/main/java/ru/mirea/practice/solutiontask1/Main.java
  students/21K0623/21K0623-p28/src/main/java/ru/mirea/practice/solutiontask2/Main.java
  students/21K0623/21K0623-p28/src/main/java/ru/mirea/practice/solutiontask2/Maps.java
  students/21K0623/21K0623-p28/src/main/java/ru/mirea/practice/solutiontask3/Main.java
  students/21K0623/21K0623-p29/pom.xml
  students/21K0623/21K0623-p29/src/main/java/ru/mirea/practice/solutiontask1/Solution.java
  students/21K0623/21K0623-p30/pom.xml
  students/21K0623/21K0623-p30/src/main/java/ru/mirea/practice/solutiontask1/Tree.java
  students/21K0623/21K0623-p30/src/main/java/ru/mirea/practice/solutiontask2/Huffman.java
  students/21K0623/21K0623-p30/src/main/java/ru/mirea/practice/solutiontask2/Main.java
  students/21K0623/21K0623-p30/src/main/java/ru/mirea/practice/solutiontask2/Tree.java
  students/21K0623/21K0623-p32/pom.xml
  students/21K0623/21K0623-p32/src/main/java/ru/mirea/practice/solutiontask1/Trotter.java
  students/21K0623/pom.xml
Labels: проверка, вопросы
